"""
Master list of ~460 Indian startups and Big Tech India offices to monitor.
Used to seed the companies table in the database.

Each entry:  { name, sector, linkedin_url, website }
linkedin_url is pre-populated where the slug is predictable; others are blank
and will be resolved lazily via Proxycurl's company search.
"""

TRACKED_COMPANIES = [
    # ── Fintech / Payments ─────────────────────────────────────────────────────
    {"name": "Paytm", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/paytm", "website": "paytm.com"},
    {"name": "PhonePe", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/phonepe-internet", "website": "phonepe.com"},
    {"name": "Razorpay", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/razorpay", "website": "razorpay.com"},
    {"name": "BharatPe", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/bharatpe", "website": "bharatpe.com"},
    {"name": "CRED", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/getcred", "website": "cred.club"},
    {"name": "PolicyBazaar", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/policybazaar", "website": "policybazaar.com"},
    {"name": "MobiKwik", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/mobikwik", "website": "mobikwik.com"},
    {"name": "Pine Labs", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/pine-labs", "website": "pinelabs.com"},
    {"name": "BillDesk", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/billdesk", "website": "billdesk.com"},
    {"name": "Slice", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/sliceit", "website": "sliceit.com"},
    {"name": "Open", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/open-financial-technologies", "website": "open.money"},
    {"name": "Yubi", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/yubi-co", "website": "yubi.co"},
    {"name": "MoneyView", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/moneyview", "website": "moneyview.in"},
    {"name": "Juspay", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/juspay", "website": "juspay.in"},
    {"name": "Dhan", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/dhan-hq", "website": "dhan.co"},
    {"name": "DMI Finance", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/dmi-finance", "website": "dmifinance.in"},
    {"name": "Groww", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/groww", "website": "groww.in"},
    {"name": "Zerodha", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/zerodha", "website": "zerodha.com"},
    {"name": "Upstox", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/upstox", "website": "upstox.com"},
    {"name": "INDmoney", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/indmoney", "website": "indmoney.com"},
    {"name": "AngelOne", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/angel-broking", "website": "angelone.in"},
    {"name": "KreditBee", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/kreditbee", "website": "kreditbee.com"},
    {"name": "Navi", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/navi-finserv", "website": "navi.com"},
    {"name": "CASHe", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/cashe", "website": "cashe.co.in"},
    {"name": "LazyPay", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/lazypay", "website": "lazypay.in"},
    {"name": "ZestMoney", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/zestmoney", "website": "zestmoney.in"},
    {"name": "Axio", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/axio-formerly-capital-float", "website": "axio.credit"},
    {"name": "EarlySalary", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/earlysalary", "website": "earlysalary.com"},
    {"name": "Stashfin", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/stashfin", "website": "stashfin.com"},
    {"name": "Kissht", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/kissht", "website": "kissht.com"},
    {"name": "Lendingkart", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/lendingkart", "website": "lendingkart.com"},
    {"name": "NeoGrowth", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/neogrowth-credit", "website": "neogrowth.in"},
    {"name": "FlexiLoans", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/flexiloans", "website": "flexiloans.com"},
    {"name": "Indifi", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/indifi-technologies", "website": "indifi.com"},
    {"name": "Aye Finance", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/aye-finance", "website": "ayefin.com"},
    {"name": "Cashfree", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/cashfree", "website": "cashfree.com"},
    {"name": "M2P Fintech", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/m2p-fintech", "website": "m2pfintech.com"},
    {"name": "PayU", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/payu", "website": "payu.in"},
    {"name": "Infibeam Avenues", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/infibeam-avenues", "website": "infibeamavenues.com"},
    {"name": "Innoviti", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/innoviti-payment-solutions", "website": "innoviti.com"},
    {"name": "Setu", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/setu-api", "website": "setu.co"},
    {"name": "Decentro", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/decentro", "website": "decentro.tech"},
    {"name": "Signzy", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/signzy", "website": "signzy.com"},
    {"name": "Perfios", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/perfios", "website": "perfios.com"},
    {"name": "Recko", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/recko", "website": "recko.com"},
    {"name": "RazorpayX", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/razorpay", "website": "razorpay.com/x"},
    {"name": "Enkash", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/enkash", "website": "enkash.com"},
    {"name": "Zaggle", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/zaggle", "website": "zaggle.in"},
    {"name": "Jupiter", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/jupiter-money", "website": "jupiter.money"},
    {"name": "Fi Money", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/epifi", "website": "fi.money"},
    {"name": "Niyo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/niyo-solutions", "website": "niyo.co"},
    {"name": "Freo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/freo-save", "website": "freo.money"},
    {"name": "Fibe", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/fibe-formerly-earlysalary", "website": "fibe.in"},
    {"name": "Smallcase", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/smallcase", "website": "smallcase.com"},
    {"name": "Kuvera", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/kuvera", "website": "kuvera.in"},
    {"name": "Fisdom", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/fisdom", "website": "fisdom.com"},
    {"name": "Scripbox", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/scripbox", "website": "scripbox.com"},
    {"name": "Stable Money", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/stable-money", "website": "stablemoney.in"},
    {"name": "5paisa", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/5paisa", "website": "5paisa.com"},
    {"name": "Acko", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/ackotech", "website": "acko.com"},
    {"name": "Digit Insurance", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/godigit", "website": "godigit.com"},
    {"name": "Turtlemint", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/turtlemint", "website": "turtlemint.com"},
    {"name": "Riskcovry", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/riskcovry", "website": "riskcovry.com"},
    {"name": "Onsurity", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/onsurity", "website": "onsurity.com"},
    {"name": "SecureNow", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/securenow", "website": "securenow.in"},
    {"name": "Zopper", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/zopper", "website": "zopper.com"},
    {"name": "Symbo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/symbo-insurance", "website": "symbo.in"},
    {"name": "Khatabook", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/khatabook", "website": "khatabook.com"},
    {"name": "OkCredit", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/okcredit", "website": "okcredit.in"},
    {"name": "BankSathi", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/banksathi", "website": "banksathi.com"},
    {"name": "Rupifi", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/rupifi", "website": "rupifi.com"},
    {"name": "Vayana Network", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/vayana-network", "website": "vayana.com"},
    {"name": "Vyapar", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/vyapar-app", "website": "vyaparapp.in"},

    # ── B2B SaaS / Enterprise Tech ─────────────────────────────────────────────
    {"name": "Freshworks", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/freshworks-inc", "website": "freshworks.com"},
    {"name": "Zoho", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/zoho-corporation", "website": "zoho.com"},
    {"name": "Chargebee", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/chargebee", "website": "chargebee.com"},
    {"name": "BrowserStack", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/browserstack", "website": "browserstack.com"},
    {"name": "Postman", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/postman-platform", "website": "postman.com"},
    {"name": "Darwinbox", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/darwinbox", "website": "darwinbox.com"},
    {"name": "Sprinklr", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/sprinklr", "website": "sprinklr.com"},
    {"name": "Icertis", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/icertis", "website": "icertis.com"},
    {"name": "Druva", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/druva-inc", "website": "druva.com"},
    {"name": "Zenoti", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/zenoti", "website": "zenoti.com"},
    {"name": "MindTickle", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/mindtickle", "website": "mindtickle.com"},
    {"name": "Uniphore", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/uniphore", "website": "uniphore.com"},
    {"name": "Innovaccer", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/innovaccer", "website": "innovaccer.com"},
    {"name": "Keka", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/keka-technologies", "website": "keka.com"},
    {"name": "greytHR", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/greythr", "website": "greythr.com"},
    {"name": "sumHR", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/sumhr", "website": "sumhr.com"},
    {"name": "HROne", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/hrone", "website": "hrone.com"},
    {"name": "Springworks", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/springworks-in", "website": "springworks.in"},
    {"name": "Kredily", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/kredily", "website": "kredily.com"},
    {"name": "Qandle", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/qandle", "website": "qandle.com"},
    {"name": "Zimyo", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/zimyo", "website": "zimyo.com"},
    {"name": "Pocket HRMS", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/pocket-hrms", "website": "pockethrms.com"},
    {"name": "Clevertap", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/clevertap", "website": "clevertap.com"},
    {"name": "MoEngage", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/moengage", "website": "moengage.com"},
    {"name": "WebEngage", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/webengage", "website": "webengage.com"},
    {"name": "Netcore", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/netcore-cloud", "website": "netcorecloud.com"},
    {"name": "Lemnisk", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/lemnisk", "website": "lemnisk.co"},
    {"name": "Capillary Technologies", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/capillary-technologies", "website": "capillarytech.com"},
    {"name": "Insider", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/useinsider", "website": "useinsider.com"},
    {"name": "iZooto", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/izooto", "website": "izooto.com"},
    {"name": "Contlo", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/contlo", "website": "contlo.com"},
    {"name": "Wigzo", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/wigzo-technologies", "website": "wigzo.com"},
    {"name": "LeadSquared", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/leadsquared", "website": "leadsquared.com"},
    {"name": "Salesken", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/salesken", "website": "salesken.ai"},
    {"name": "Kapture CRM", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/kapture-crm", "website": "kapturecrm.com"},
    {"name": "Skit.ai", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/skit-ai", "website": "skit.ai"},
    {"name": "Exotel", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/exotel", "website": "exotel.com"},
    {"name": "Ozonetel", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/ozonetel", "website": "ozonetel.com"},
    {"name": "Ameyo", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/ameyo-drishti-soft", "website": "ameyo.com"},
    {"name": "Hiver", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/hiverhq", "website": "hiverhq.com"},
    {"name": "Freshdesk", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/freshworks-inc", "website": "freshdesk.com"},
    {"name": "Helpshift", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/helpshift", "website": "helpshift.com"},
    {"name": "Gupshup", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/gupshup-io", "website": "gupshup.io"},
    {"name": "Kaleyra", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/kaleyra", "website": "kaleyra.com"},
    {"name": "Route Mobile", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/route-mobile-limited", "website": "routemobile.com"},
    {"name": "Tanla Platforms", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/tanla-platforms", "website": "tanla.com"},
    {"name": "ValueFirst", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/valuefirst", "website": "vfirst.com"},
    {"name": "Hasura", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/hasura", "website": "hasura.io"},
    {"name": "Appsmith", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/appsmith-hq", "website": "appsmith.com"},
    {"name": "DhiWise", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/dhiwise", "website": "dhiwise.com"},
    {"name": "Keploy", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/keploy", "website": "keploy.io"},
    {"name": "Devrev", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/devrev", "website": "devrev.ai"},
    {"name": "Middleware", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/middleware-io", "website": "middleware.io"},
    {"name": "Requestly", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/requestly", "website": "requestly.io"},
    {"name": "Appknox", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/appknox", "website": "appknox.com"},
    {"name": "Indusface", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/indusface", "website": "indusface.com"},
    {"name": "Whatfix", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/whatfix", "website": "whatfix.com"},
    {"name": "Leapsome", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/leapsome", "website": "leapsome.com"},
    {"name": "Happay", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/happay", "website": "happay.in"},
    {"name": "Fyle", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/fyle-it", "website": "fylehq.com"},
    {"name": "Volopay", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/volopay", "website": "volopay.com"},
    {"name": "Finly", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/finly", "website": "finly.io"},
    {"name": "Fractal Analytics", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/fractal-analytics", "website": "fractal.ai"},
    {"name": "Mu Sigma", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/mu-sigma-inc", "website": "mu-sigma.com"},
    {"name": "Sigmoid", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/sigmoid", "website": "sigmoid.com"},
    {"name": "Slintel", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/slintel", "website": "slintel.com"},
    {"name": "Clodura", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/clodura-ai", "website": "clodura.ai"},
    {"name": "Draup", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/draup", "website": "draup.com"},
    {"name": "Crayon Data", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/crayon-data", "website": "crayondata.com"},
    {"name": "Toplyne", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/toplyne", "website": "toplyne.io"},
    {"name": "Suprsend", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/suprsend", "website": "suprsend.com"},
    {"name": "Nanonets", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/nanonets", "website": "nanonets.com"},
    {"name": "Docsumo", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/docsumo", "website": "docsumo.com"},
    {"name": "Tagalys", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/tagalys", "website": "tagalys.com"},
    {"name": "Refrens", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/refrens", "website": "refrens.com"},
    {"name": "Deskera", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/deskera", "website": "deskera.com"},
    {"name": "TranZact", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/tranzact-in", "website": "tranzact.in"},
    {"name": "Tally Solutions", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/tally-solutions", "website": "tallysolutions.com"},
    {"name": "Busy Infotech", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/busy-infotech", "website": "busywin.com"},
    {"name": "Marg ERP", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/marg-erp-ltd", "website": "margcompusoft.com"},

    # ── Ecommerce & Marketplaces ────────────────────────────────────────────────
    {"name": "Flipkart", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/flipkart", "website": "flipkart.com"},
    {"name": "Meesho", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/meesho", "website": "meesho.com"},
    {"name": "Nykaa", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/nykaa", "website": "nykaa.com"},
    {"name": "Snapdeal", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/snapdeal", "website": "snapdeal.com"},
    {"name": "FirstCry", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/firstcry-com", "website": "firstcry.com"},
    {"name": "IndiaMART", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/indiamart", "website": "indiamart.com"},
    {"name": "Purplle", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/purplle", "website": "purplle.com"},
    {"name": "GlobalBees", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/globalbees", "website": "globalbees.com"},
    {"name": "Cars24", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/cars24", "website": "cars24.com"},
    {"name": "CarDekho", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/cardekho", "website": "cardekho.com"},
    {"name": "Spinny", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/spinny", "website": "spinny.com"},
    {"name": "Droom", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/droom", "website": "droom.in"},
    {"name": "CarTrade", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/cartrade", "website": "cartrade.com"},
    {"name": "NoBroker", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/nobroker", "website": "nobroker.in"},
    {"name": "Housing.com", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/housing-com", "website": "housing.com"},
    {"name": "MagicBricks", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/magicbricks", "website": "magicbricks.com"},
    {"name": "99acres", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/99acres", "website": "99acres.com"},
    {"name": "Square Yards", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/squareyards", "website": "squareyards.com"},
    {"name": "PropTiger", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/proptiger", "website": "proptiger.com"},
    {"name": "Anarock", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/anarock", "website": "anarock.com"},
    {"name": "Livspace", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/livspace", "website": "livspace.com"},
    {"name": "Urban Company", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/urban-company", "website": "urbancompany.com"},
    {"name": "Housejoy", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/housejoy", "website": "housejoy.in"},
    {"name": "Quikr", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/quikr", "website": "quikr.com"},
    {"name": "OLX India", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/olx-india", "website": "olx.in"},
    {"name": "Sulekha", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/sulekha", "website": "sulekha.com"},
    {"name": "JustDial", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/justdial", "website": "justdial.com"},
    {"name": "Matrimony.com", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/matrimony-com", "website": "matrimony.com"},
    {"name": "BharatMatrimony", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/bharatmatrimony", "website": "bharatmatrimony.com"},
    {"name": "Myntra", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/myntra", "website": "myntra.com"},
    {"name": "Limeroad", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/limeroad", "website": "limeroad.com"},
    {"name": "Craftsvilla", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/craftsvilla", "website": "craftsvilla.com"},
    {"name": "Fashor", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/fashor", "website": "fashor.com"},
    {"name": "BlueStone", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/bluestone-com", "website": "bluestone.com"},
    {"name": "Melorra", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/melorra", "website": "melorra.com"},
    {"name": "Caratlane", "sector": "Ecommerce", "linkedin_url": "https://www.linkedin.com/company/caratlane", "website": "caratlane.com"},

    # ── Quick Commerce / Logistics ─────────────────────────────────────────────
    {"name": "Zepto", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/zeptonow", "website": "zeptonow.com"},
    {"name": "Blinkit", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/blinkit", "website": "blinkit.com"},
    {"name": "Swiggy Instamart", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/swiggy", "website": "swiggy.com"},
    {"name": "BigBasket", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/bigbasket-com", "website": "bigbasket.com"},
    {"name": "Dunzo", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/dunzo", "website": "dunzo.com"},
    {"name": "Country Delight", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/country-delight", "website": "countrydelight.in"},
    {"name": "Milkbasket", "sector": "Quick Commerce", "linkedin_url": "https://www.linkedin.com/company/milkbasket", "website": "milkbasket.com"},
    {"name": "Delhivery", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/delhivery", "website": "delhivery.com"},
    {"name": "Shiprocket", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/shiprocket", "website": "shiprocket.in"},
    {"name": "Xpressbees", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/xpressbees", "website": "xpressbees.com"},
    {"name": "ElasticRun", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/elasticrun", "website": "elasticrun.com"},
    {"name": "Rivigo", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/rivigo", "website": "rivigo.com"},
    {"name": "BlackBuck", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/blackbuck", "website": "blackbuck.com"},
    {"name": "Porter", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/porter-logistics", "website": "porter.in"},
    {"name": "Shadowfax", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/shadowfax", "website": "shadowfax.in"},
    {"name": "Loadshare", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/loadshare-networks", "website": "loadshare.net"},
    {"name": "Pickrr", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/pickrr", "website": "pickrr.com"},
    {"name": "Blowhorn", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/blowhorn", "website": "blowhorn.com"},
    {"name": "Vamaship", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/vamaship", "website": "vamaship.com"},
    {"name": "Shipway", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/shipway", "website": "shipway.in"},
    {"name": "Ezyslips", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/ezyslips", "website": "ezyslips.com"},
    {"name": "iThink Logistics", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/ithink-logistics", "website": "ithinklogistics.com"},
    {"name": "Shyplite", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/shyplite", "website": "shyplite.com"},
    {"name": "Pidge", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/pidge-in", "website": "pidge.in"},
    {"name": "Borzo", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/borzo-delivery", "website": "borzo.com"},
    {"name": "WeFast", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/wefast", "website": "wefast.com"},
    {"name": "Locus", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/locus-sh", "website": "locus.sh"},
    {"name": "FarEye", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/fareye", "website": "fareye.com"},
    {"name": "LogiNext", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/loginext-solutions", "website": "loginextsolutions.com"},
    {"name": "Fleetx", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/fleetx", "website": "fleetx.io"},
    {"name": "Intugine", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/intugine", "website": "intugine.com"},
    {"name": "Moveinsync", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/moveinsync", "website": "moveinsync.com"},
    {"name": "Vinculum", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/vinculum-solutions", "website": "vinculumgroup.com"},
    {"name": "Increff", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/increff", "website": "increff.com"},
    {"name": "Anchanto", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/anchanto", "website": "anchanto.com"},
    {"name": "Unicommerce", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/unicommerce", "website": "unicommerce.com"},
    {"name": "StoreHippo", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/storehippo", "website": "storehippo.com"},

    # ── B2B Commerce & Manufacturing ───────────────────────────────────────────
    {"name": "Zetwerk", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/zetwerk", "website": "zetwerk.com"},
    {"name": "OfBusiness", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/ofbusiness", "website": "ofbusiness.com"},
    {"name": "Moglix", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/moglix", "website": "moglix.com"},
    {"name": "Udaan", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/udaan-com", "website": "udaan.com"},
    {"name": "Infra.Market", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/inframarket", "website": "infra.market"},
    {"name": "Jumbotail", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/jumbotail", "website": "jumbotail.com"},
    {"name": "Ninjacart", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/ninjacart", "website": "ninjacart.in"},
    {"name": "DeHaat", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/dehaat", "website": "dehaat.com"},
    {"name": "WayCool", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/waycool-foods", "website": "waycool.in"},
    {"name": "Bijak", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/bijak-app", "website": "bijak.in"},
    {"name": "Jai Kisan", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/jai-kisan", "website": "jaikisan.co"},
    {"name": "AgroStar", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/agrostar", "website": "agrostar.in"},
    {"name": "Captain Fresh", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/captain-fresh", "website": "captainfresh.com"},
    {"name": "Vegrow", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/vegrow", "website": "vegrow.in"},
    {"name": "ProcMart", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/procmart", "website": "procmart.com"},
    {"name": "Mjunction", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/mjunction-services", "website": "mjunction.in"},
    {"name": "Power2SME", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/power2sme", "website": "power2sme.com"},
    {"name": "Shotang", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/shotang", "website": "shotang.com"},
    {"name": "Metalbook", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/metalbook", "website": "metalbook.in"},
    {"name": "Fashinza", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/fashinza", "website": "fashinza.com"},
    {"name": "Sourcewiz", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/sourcewiz", "website": "sourcewiz.co"},
    {"name": "Credlix", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/credlix", "website": "credlix.com"},
    {"name": "Drip Capital", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/drip-capital", "website": "dripcapital.com"},
    {"name": "Stenn India", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/stenn-international", "website": "stenn.com"},
    {"name": "FactoryPlus", "sector": "B2B Commerce", "linkedin_url": "https://www.linkedin.com/company/factoryplus", "website": "factoryplus.co"},

    # ── Consumer & D2C ─────────────────────────────────────────────────────────
    {"name": "Mamaearth", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/mamaearth", "website": "mamaearth.in"},
    {"name": "boAt", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/boat-lifestyle", "website": "boat-lifestyle.com"},
    {"name": "Lenskart", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/lenskart", "website": "lenskart.com"},
    {"name": "Nykaa Fashion", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/nykaa", "website": "nykaafashion.com"},
    {"name": "Sugar Cosmetics", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/sugar-cosmetics", "website": "sugarcosmetics.com"},
    {"name": "Minimalist", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/minimalist-co", "website": "beminimalist.co"},
    {"name": "Pilgrim", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/pilgrim-india", "website": "pilgrim.in"},
    {"name": "Plum", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/plum-goodness", "website": "plumgoodness.com"},
    {"name": "mCaffeine", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/mcaffeine", "website": "mcaffeine.com"},
    {"name": "The Moms Co", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/the-moms-co", "website": "themomsco.com"},
    {"name": "Wow Skin", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/wow-skin-science", "website": "buywow.in"},
    {"name": "Beardo", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/beardo", "website": "beardo.in"},
    {"name": "Man Company", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/the-man-company", "website": "themancompany.com"},
    {"name": "Bombay Shaving", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/bombay-shaving-company", "website": "bombayshavingcompany.com"},
    {"name": "Ustraa", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/ustraa", "website": "ustraa.com"},
    {"name": "Pee Safe", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/pee-safe", "website": "peesafe.com"},
    {"name": "Sirona", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/sirona-hygiene", "website": "sironahygiene.com"},
    {"name": "Bella Vita", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/bella-vita-organic", "website": "bellavitaorganic.com"},
    {"name": "Just Herbs", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/just-herbs", "website": "justherbs.in"},
    {"name": "Juicy Chemistry", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/juicy-chemistry", "website": "juicychemistry.com"},
    {"name": "Fixderma", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/fixderma-india", "website": "fixderma.com"},
    {"name": "Dot & Key", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/dot-and-key", "website": "dotandkey.com"},
    {"name": "Re'equil", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/reequil", "website": "reequil.com"},
    {"name": "Wakefit", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/wakefit", "website": "wakefit.co"},
    {"name": "Sleep Company", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/the-sleep-company", "website": "thesleepcompany.in"},
    {"name": "Pepperfry", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/pepperfry", "website": "pepperfry.com"},
    {"name": "Urban Ladder", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/urban-ladder", "website": "urbanladder.com"},
    {"name": "Duroflex", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/duroflex", "website": "duroflex.com"},
    {"name": "Bewakoof", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/bewakoof-com", "website": "bewakoof.com"},
    {"name": "Clovia", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/clovia", "website": "clovia.com"},
    {"name": "Zivame", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/zivame", "website": "zivame.com"},
    {"name": "Nykd", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/nykd-by-nykaa", "website": "nykd.com"},
    {"name": "Libas", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/libasindia", "website": "libas.in"},
    {"name": "Aurelia", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/aurelia-fashion", "website": "aurelia.in"},
    {"name": "Licious", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/licious", "website": "licious.in"},
    {"name": "Epigamia", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/epigamia", "website": "epigamia.com"},
    {"name": "Raw Pressery", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/raw-pressery", "website": "rawpressery.com"},
    {"name": "Slurrp Farm", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/slurrp-farm", "website": "slurrpfarm.com"},
    {"name": "Yoga Bar", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/yogabar", "website": "yogabar.in"},
    {"name": "Oziva", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/oziva", "website": "oziva.in"},
    {"name": "The Good Bug", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/the-good-bug", "website": "thegoodbug.com"},
    {"name": "Kapiva", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/kapiva", "website": "kapiva.in"},
    {"name": "Rage Coffee", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/rage-coffee", "website": "ragecoffee.in"},
    {"name": "Sleepy Owl", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/sleepy-owl", "website": "sleepyowl.co"},
    {"name": "Drums Food", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/drums-food-international", "website": "drumsfood.com"},
    {"name": "Noise", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/gonoise", "website": "gonoise.com"},
    {"name": "Fire-Boltt", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/fire-boltt", "website": "fire-boltt.com"},
    {"name": "Mivi", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/mivi-india", "website": "mivi.in"},
    {"name": "CrossBeats", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/crossbeats", "website": "crossbeats.com"},
    {"name": "Boult Audio", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/boult-audio", "website": "boultaudio.com"},
    {"name": "Zebronics", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/zebronics-india", "website": "zebronics.com"},
    {"name": "Drools", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/droolsindia", "website": "drools.in"},
    {"name": "Heads Up For Tails", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/heads-up-for-tails", "website": "headsupfortails.com"},
    {"name": "Supertails", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/supertails", "website": "supertails.com"},
    {"name": "Wiggles", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/wiggles-india", "website": "wigglespet.com"},
    {"name": "BabyChakra", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/babychakra", "website": "babychakra.com"},
    {"name": "Hopscotch", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/hopscotch-in", "website": "hopscotch.in"},
    {"name": "The Nestery", "sector": "Consumer D2C", "linkedin_url": "https://www.linkedin.com/company/the-nestery", "website": "thenestery.in"},

    # ── Mobility & EV ──────────────────────────────────────────────────────────
    {"name": "Ola", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/olacabs", "website": "olacabs.com"},
    {"name": "Rapido", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/rapido", "website": "rapido.bike"},
    {"name": "BluSmart", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/blusmart", "website": "blusmart.in"},
    {"name": "Ola Electric", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/olaelectric", "website": "olaelectric.com"},
    {"name": "Ather Energy", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/ather-energy", "website": "atherenergy.com"},
    {"name": "Revolt Motors", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/revolt-motors", "website": "revoltmotors.in"},
    {"name": "Simple Energy", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/simple-energy", "website": "simpleenergy.in"},
    {"name": "Ultraviolette", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/ultraviolette-automotive", "website": "ultraviolette.co"},
    {"name": "Euler Motors", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/euler-motors", "website": "eulermotors.com"},
    {"name": "Log9 Materials", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/log9materials", "website": "log9materials.com"},
    {"name": "Exponent Energy", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/exponent-energy", "website": "exponent.energy"},
    {"name": "BattRE", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/battre-electric-mobility", "website": "battre.in"},
    {"name": "Ampere Vehicles", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/ampere-vehicles", "website": "amperevehicles.in"},
    {"name": "Okinawa", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/okinawa-autotech", "website": "okinawa.in"},
    {"name": "Hero Electric", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/hero-electric", "website": "heroelectric.in"},
    {"name": "Statiq", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/statiq", "website": "statiq.in"},
    {"name": "ChargeZone", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/chargezone", "website": "chargezone.in"},
    {"name": "Kazam", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/kazam-ev", "website": "kazam.in"},
    {"name": "ElectricPe", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/electricpe", "website": "electricpe.in"},
    {"name": "Bolt.Earth", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/bolt-earth", "website": "bolt.earth"},
    {"name": "Glida", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/glida-in", "website": "glida.in"},
    {"name": "Volttic", "sector": "EV", "linkedin_url": "https://www.linkedin.com/company/volttic", "website": "volttic.com"},
    {"name": "Yulu", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/yuluride", "website": "yulu.bike"},
    {"name": "Bounce", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/bounce-scooters", "website": "bounce.bike"},
    {"name": "Vogo", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/vogo-automotive", "website": "vogoauto.com"},
    {"name": "Zoomcar", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/zoomcar", "website": "zoomcar.com"},
    {"name": "Revv", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/revv", "website": "revv.co"},
    {"name": "Drivezy", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/drivezy", "website": "drivezy.com"},
    {"name": "GoMechanic", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/gomechanic", "website": "gomechanic.in"},
    {"name": "Pitstop", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/pitstop-in", "website": "pitstop.in"},
    {"name": "Carcility", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/carcility", "website": "carcility.com"},
    {"name": "Park+", "sector": "Mobility", "linkedin_url": "https://www.linkedin.com/company/parkplus", "website": "parkplus.io"},

    # ── Foodtech & QSR ─────────────────────────────────────────────────────────
    {"name": "Swiggy", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/swiggy", "website": "swiggy.com"},
    {"name": "Zomato", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/zomato", "website": "zomato.com"},
    {"name": "Rebel Foods", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/rebel-foods", "website": "rebelfoods.com"},
    {"name": "EatSure", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/rebel-foods", "website": "eatsure.com"},
    {"name": "Biryani By Kilo", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/biryani-by-kilo", "website": "biryanibykilo.com"},
    {"name": "Faasos", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/rebel-foods", "website": "faasos.com"},
    {"name": "Box8", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/box8", "website": "box8.in"},
    {"name": "Freshmenu", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/freshmenu", "website": "freshmenu.com"},
    {"name": "Innerchef", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/innerchef", "website": "innerchef.com"},
    {"name": "Burger Singh", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/burger-singh", "website": "burgersingh.com"},
    {"name": "Wow Momo", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/wow-momo-foods", "website": "wowmomo.com"},
    {"name": "Goli Vada Pav", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/goli-vada-pav", "website": "golivadapav.com"},
    {"name": "Chai Point", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/chai-point", "website": "chaipoint.com"},
    {"name": "Chaayos", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/chaayos", "website": "chaayos.com"},
    {"name": "Third Wave Coffee", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/third-wave-coffee", "website": "thirdwavecoffee.in"},
    {"name": "Blue Tokai", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/blue-tokai-coffee-roasters", "website": "bluetokaicoffee.com"},
    {"name": "Dotpe", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/dotpe", "website": "dotpe.in"},
    {"name": "UrbanPiper", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/urbanpiper", "website": "urbanpiper.com"},
    {"name": "Petpooja", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/petpooja", "website": "petpooja.com"},
    {"name": "Posist", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/posist", "website": "posist.com"},
    {"name": "Torqus", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/torqus-systems", "website": "torqus.com"},
    {"name": "Dineout", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/dineout", "website": "dineout.co.in"},
    {"name": "EazyDiner", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/eazydiner", "website": "eazydiner.com"},
    {"name": "Magicpin", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/magicpin", "website": "magicpin.in"},
    {"name": "Nearbuy", "sector": "Foodtech", "linkedin_url": "https://www.linkedin.com/company/nearbuy", "website": "nearbuy.com"},

    # ── Travel & Hospitality ────────────────────────────────────────────────────
    {"name": "OYO", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/oyorooms", "website": "oyorooms.com"},
    {"name": "MakeMyTrip", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/makemytrip", "website": "makemytrip.com"},
    {"name": "Ixigo", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/ixigo", "website": "ixigo.com"},
    {"name": "RateGain", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/rategain", "website": "rategain.com"},
    {"name": "Treebo", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/treebo", "website": "treebo.com"},
    {"name": "FabHotels", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/fabhotels", "website": "fabhotels.com"},
    {"name": "StayVista", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/stayvista", "website": "stayvista.com"},
    {"name": "Zostel", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/zostel", "website": "zostel.com"},
    {"name": "Moustache Escapes", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/moustache-escapes", "website": "moustacheescapes.com"},
    {"name": "Vista Rooms", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/vista-rooms", "website": "vistarooms.com"},
    {"name": "Lohono Stays", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/lohono", "website": "lohono.com"},
    {"name": "Cleartrip", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/cleartrip", "website": "cleartrip.com"},
    {"name": "Yatra", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/yatra-online-pvt-ltd", "website": "yatra.com"},
    {"name": "EaseMyTrip", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/easemytrip", "website": "easemytrip.com"},
    {"name": "Thrillophilia", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/thrillophilia", "website": "thrillophilia.com"},
    {"name": "Holidify", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/holidify", "website": "holidify.com"},
    {"name": "Tripoto", "sector": "Travel", "linkedin_url": "https://www.linkedin.com/company/tripoto", "website": "tripoto.com"},

    # ── Gaming & Creator Economy ────────────────────────────────────────────────
    {"name": "Dream11", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/dream11", "website": "dream11.com"},
    {"name": "MPL", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/mobile-premier-league", "website": "mpl.live"},
    {"name": "Games24x7", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/games24x7", "website": "games24x7.com"},
    {"name": "Nazara Technologies", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/nazara-technologies", "website": "nazara.com"},
    {"name": "WinZO", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/winzo-games", "website": "winzogames.com"},
    {"name": "Rario", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/rario", "website": "rario.com"},
    {"name": "FanClash", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/fanclash", "website": "fanclash.com"},
    {"name": "Rooter", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/rooter", "website": "rooter.gg"},
    {"name": "Loco", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/loco-live", "website": "loco.gg"},
    {"name": "Gameskraft", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/gameskraft", "website": "gameskraft.com"},
    {"name": "PlaySimple", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/playsimple-games", "website": "playsimplegames.com"},
    {"name": "JetSynthesys", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/jetsynthesys", "website": "jetsynthesys.com"},
    {"name": "99Games", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/99games", "website": "99games.in"},
    {"name": "ShareChat", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/sharechat", "website": "sharechat.com"},
    {"name": "Moj", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/sharechat", "website": "mojapp.in"},
    {"name": "Koo", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/kooapp", "website": "kooapp.com"},
    {"name": "Josh", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/dailyhunt", "website": "josh.app"},
    {"name": "Trell", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/trell", "website": "trell.co"},
    {"name": "Chingari", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/chingari", "website": "chingari.io"},
    {"name": "Kutumb", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/kutumbapp", "website": "kutumb.app"},
    {"name": "Lokal", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/lokal-app", "website": "lokal.so"},
    {"name": "Pratilipi", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/pratilipi", "website": "pratilipi.com"},
    {"name": "Pocket FM", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/pocket-fm", "website": "pocketfm.com"},
    {"name": "Kuku FM", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/kuku-fm", "website": "kukufm.com"},
    {"name": "Graphy", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/graphy-inc", "website": "graphy.com"},
    {"name": "Frnd", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/frnd-app", "website": "frnd.app"},
    {"name": "Stage", "sector": "Creator Economy", "linkedin_url": "https://www.linkedin.com/company/stage-ott", "website": "stage.in"},

    # ── Healthtech ─────────────────────────────────────────────────────────────
    {"name": "PharmEasy", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/pharmeasy", "website": "pharmeasy.in"},
    {"name": "Pristyn Care", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/pristyn-care", "website": "pristyncare.com"},
    {"name": "Curefit", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/curefit", "website": "cure.fit"},
    {"name": "1mg", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/1mg", "website": "1mg.com"},
    {"name": "Practo", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/practo", "website": "practo.com"},
    {"name": "Ultrahuman", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/ultrahuman", "website": "ultrahuman.com"},
    {"name": "Eka Care", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/eka-care", "website": "eka.care"},
    {"name": "Healthplix", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/healthplix", "website": "healthplix.com"},
    {"name": "Mfine", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/mfine", "website": "mfine.co"},
    {"name": "Portea", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/portea-medical", "website": "portea.com"},
    {"name": "Dozee", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/dozee", "website": "dozee.io"},
    {"name": "Tricog", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/tricog", "website": "tricog.com"},
    {"name": "Qure.ai", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/qure-ai", "website": "qure.ai"},
    {"name": "Tata 1mg", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/1mg", "website": "1mg.com"},
    {"name": "Netmeds", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/netmeds", "website": "netmeds.com"},
    {"name": "Apollo Pharmacy Online", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/apollo-pharmacy", "website": "apollopharmacy.in"},
    {"name": "MediBuddy", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/medibuddy", "website": "medibuddy.in"},
    {"name": "Myupchar", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/myupchar", "website": "myupchar.com"},
    {"name": "Medkart", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/medkart", "website": "medkart.in"},
    {"name": "YourDOST", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/yourdost", "website": "yourdost.com"},
    {"name": "Wysa", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/wysa", "website": "wysa.io"},
    {"name": "InnerHour", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/innerhour", "website": "theinnerhour.com"},
    {"name": "Mindhouse", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/mindhouse", "website": "mindhouse.com"},
    {"name": "Fitterfly", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/fitterfly", "website": "fitterfly.com"},
    {"name": "Sugarfit", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/sugarfit", "website": "sugarfit.com"},
    {"name": "Cult.fit", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/curefit", "website": "cult.fit"},
    {"name": "Plum Benefits", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/plumhq", "website": "plumhq.com"},
    {"name": "Nova Benefits", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/nova-benefits", "website": "novabenefits.com"},
    {"name": "Loop Health", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/loop-health", "website": "loophealth.com"},
    {"name": "Niva Bupa", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/niva-bupa-health-insurance", "website": "nivabupa.com"},
    {"name": "Digit Health", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/godigit", "website": "godigit.com"},
    {"name": "Lybrate", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/lybrate", "website": "lybrate.com"},
    {"name": "DocsApp", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/docsapp", "website": "docsapp.in"},
    {"name": "iCliniq", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/icliniq", "website": "icliniq.com"},
    {"name": "Clinikally", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/clinikally", "website": "clinikally.com"},

    # ── Edtech ─────────────────────────────────────────────────────────────────
    {"name": "PhysicsWallah", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/physicswallah", "website": "pw.live"},
    {"name": "Byju's", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/byjus", "website": "byjus.com"},
    {"name": "Unacademy", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/unacademy", "website": "unacademy.com"},
    {"name": "upGrad", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/upgrad-com", "website": "upgrad.com"},
    {"name": "Eruditus", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/eruditus-executive-education", "website": "eruditus.com"},
    {"name": "Vedantu", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/vedantu", "website": "vedantu.com"},
    {"name": "Scaler", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/scaler-academy", "website": "scaler.com"},
    {"name": "Great Learning", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/great-learning", "website": "mygreatlearning.com"},
    {"name": "Simplilearn", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/simplilearn", "website": "simplilearn.com"},
    {"name": "Coding Ninjas", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/coding-ninjas", "website": "codingninjas.com"},
    {"name": "Newton School", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/newton-school", "website": "newtonschool.co"},
    {"name": "Masai School", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/masai-school", "website": "masaischool.com"},
    {"name": "Classplus", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/classplus", "website": "classplusapp.com"},
    {"name": "Teachmint", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/teachmint", "website": "teachmint.com"},
    {"name": "Practically", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/practically", "website": "practically.com"},
    {"name": "iNeuron", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/ineuron-intelligence", "website": "ineuron.ai"},
    {"name": "Sunstone", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/sunstone-edu", "website": "sunstone.edu.in"},
    {"name": "Hero Vired", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/hero-vired", "website": "herovired.com"},
    {"name": "Unstop", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/unstop", "website": "unstop.com"},
    {"name": "Prepladder", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/prepladder", "website": "prepladder.com"},
    {"name": "Testbook", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/testbook", "website": "testbook.com"},
    {"name": "Adda247", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/adda247", "website": "adda247.com"},
    {"name": "InterviewBit", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/interviewbit", "website": "interviewbit.com"},
    {"name": "Springboard", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/springboard-online", "website": "springboard.com"},
    {"name": "Emeritus", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/emeritus-institute-of-management", "website": "emeritus.org"},
    {"name": "Imarticus", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/imarticus-learning", "website": "imarticus.org"},
    {"name": "TimesPro", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/timespro", "website": "timespro.com"},
    {"name": "Jaro Education", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/jaro-education", "website": "jaroeducation.com"},
    {"name": "Learnbay", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/learnbay", "website": "learnbay.co"},
    {"name": "Entri", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/entri-app", "website": "entri.me"},
    {"name": "Josh Talks", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/josh-talks", "website": "joshtalks.com"},
    {"name": "Seekho", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/seekho", "website": "seekho.ai"},
    {"name": "WhiteHat Jr", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/whitehat-education-technology", "website": "whitehatjr.com"},
    {"name": "Cuemath", "sector": "Edtech", "linkedin_url": "https://www.linkedin.com/company/cuemath", "website": "cuemath.com"},

    # ── AI / ML ────────────────────────────────────────────────────────────────
    {"name": "Sarvam AI", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/sarvam-ai", "website": "sarvam.ai"},
    {"name": "Krutrim", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/krutrim-si-designs", "website": "krutrim.com"},
    {"name": "Yellow.ai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/yellowmessenger", "website": "yellow.ai"},
    {"name": "Haptik", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/haptik", "website": "haptik.ai"},
    {"name": "Gnani.ai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/gnani-ai", "website": "gnani.ai"},
    {"name": "Mad Street Den", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/mad-street-den", "website": "madstreetden.com"},
    {"name": "Arya.ai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/arya-ai", "website": "arya.ai"},
    {"name": "Observe.AI", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/observe-ai", "website": "observe.ai"},
    {"name": "Vernacular.ai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/vernacularai", "website": "vernacular.ai"},
    {"name": "Staqu", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/staqu", "website": "staqu.com"},
    {"name": "SigTuple", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/sigtuple", "website": "sigtuple.com"},
    {"name": "Niramai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/niramai", "website": "niramai.com"},
    {"name": "Detect Technologies", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/detect-technologies", "website": "detect.com"},
    {"name": "Mihup", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/mihup", "website": "mihup.com"},
    {"name": "Slang Labs", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/slang-labs", "website": "slanglabs.in"},
    {"name": "Vahan", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/vahan-inc", "website": "vahan.co"},
    {"name": "SquadStack", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/squadstack", "website": "squadstack.com"},
    {"name": "Entropik Tech", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/entropik-tech", "website": "entropiktech.com"},
    {"name": "Leena AI", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/leena-ai", "website": "leena.ai"},
    {"name": "Senseforth", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/senseforth", "website": "senseforth.com"},
    {"name": "Niki.ai", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/nikiapp", "website": "niki.ai"},
    {"name": "Uncanny Vision", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/uncanny-vision", "website": "uncannyvision.com"},
    {"name": "E2E Networks", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/e2e-networks", "website": "e2enetworks.com"},
    {"name": "Yotta Infrastructure", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/yotta-infrastructure", "website": "yottainfrastructure.com"},
    {"name": "ESDS Software", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/esds-software-solution", "website": "esds.co.in"},
    {"name": "Netradyne", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/netradyne", "website": "netradyne.com"},
    {"name": "Pixis", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/pixis-co", "website": "pixis.co"},
    {"name": "Scribble Data", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/scribble-data", "website": "scribbledata.io"},
    {"name": "Kellton Tech", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/kellton-tech", "website": "kelltontech.com"},
    {"name": "CoRover", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/corover", "website": "corover.ai"},
    {"name": "Floatbot", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/floatbot", "website": "floatbot.ai"},
    {"name": "Engati", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/engati", "website": "engati.com"},
    {"name": "IMImobile", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/imimobile", "website": "imimobile.com"},
    {"name": "Frrole", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/frrole", "website": "frrole.com"},
    {"name": "Innefu Labs", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/innefu-labs", "website": "innefu.com"},
    {"name": "IDfy", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/idfy", "website": "idfy.com"},
    {"name": "AuthBridge", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/authbridge", "website": "authbridge.com"},

    # ── Climate / Agri & Deeptech ───────────────────────────────────────────────
    {"name": "Gramophone", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/gramophone-india", "website": "gramophone.in"},
    {"name": "BharatAgri", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/bharatagri", "website": "bharatagri.com"},
    {"name": "Agribazaar", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/agribazaar", "website": "agribazaar.com"},
    {"name": "Intello Labs", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/intello-labs", "website": "intellolabs.com"},
    {"name": "AgNext", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/agnext-technologies", "website": "agnext.com"},
    {"name": "Stellapps", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/stellapps-technologies", "website": "stellapps.com"},
    {"name": "Eruvaka", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/eruvaka-technologies", "website": "eruvaka.com"},
    {"name": "Cropin", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/cropin", "website": "cropin.com"},
    {"name": "CleanMax", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/cleanmax-solar", "website": "cleanmax.com"},
    {"name": "Climes", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/climes-carbon", "website": "climes.in"},
    {"name": "Varaha", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/varaha", "website": "varaha.earth"},
    {"name": "Boomitra", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/boomitra", "website": "boomitra.com"},
    {"name": "GreenCell", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/greencell-mobility", "website": "greencellmobility.com"},
    {"name": "EcoSoul Home", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/ecosoul-home", "website": "ecosoulhome.com"},
    {"name": "Sterlite Power", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/sterlite-power", "website": "sterlitepower.com"},
    {"name": "ReNew Power", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/renew-power", "website": "renewpower.in"},
    {"name": "Greenko", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/greenko-group", "website": "greenko.in"},
    {"name": "Azure Power", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/azure-power", "website": "azurepower.com"},
    {"name": "Sprng Energy", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/sprng-energy", "website": "sprng.in"},
    {"name": "Saahas Zero Waste", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/saahas-zero-waste", "website": "saahas.org"},
    {"name": "Recykal", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/recykal", "website": "recykal.com"},
    {"name": "Kabadiwalla Connect", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/kabadiwalla-connect", "website": "kabadiwallaconnect.in"},
    {"name": "Hasiru Dala", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/hasiru-dala", "website": "hasirudala.in"},
    {"name": "Nepra", "sector": "Climate Tech", "linkedin_url": "https://www.linkedin.com/company/nepra-resource-management", "website": "nepra.in"},
    {"name": "Agnikul Cosmos", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/agnikul", "website": "agnikul.in"},
    {"name": "Skyroot Aerospace", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/skyroot-aerospace", "website": "skyroot.in"},
    {"name": "Pixxel", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/pixxel", "website": "pixxel.space"},
    {"name": "Bellatrix Aerospace", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/bellatrix-aerospace", "website": "bellatrixaerospace.com"},
    {"name": "Satsure", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/satsure", "website": "satsure.co"},
    {"name": "GalaxEye", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/galaxeye-space", "website": "galaxeye.space"},
    {"name": "Dhruva Space", "sector": "Deeptech", "linkedin_url": "https://www.linkedin.com/company/dhruva-space", "website": "dhruvaspace.com"},
    {"name": "Samunnati", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/samunnati", "website": "samunnati.com"},

    # ── Big Tech India & MNCs ──────────────────────────────────────────────────
    {"name": "Google India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/google", "website": "google.co.in"},
    {"name": "Microsoft India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/microsoft", "website": "microsoft.com/en-in"},
    {"name": "Meta India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/meta", "website": "meta.com"},
    {"name": "Amazon India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/amazon", "website": "amazon.in"},
    {"name": "Apple India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/apple", "website": "apple.com/in"},
    {"name": "Salesforce India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/salesforce", "website": "salesforce.com"},
    {"name": "Adobe India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/adobe", "website": "adobe.com"},
    {"name": "Oracle India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/oracle", "website": "oracle.com"},
    {"name": "IBM India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/ibm", "website": "ibm.com/in"},
    {"name": "Cisco India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/cisco", "website": "cisco.com"},
    {"name": "Qualcomm India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/qualcomm", "website": "qualcomm.com"},
    {"name": "Intel India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/intel-corporation", "website": "intel.com"},
    {"name": "Nvidia India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/nvidia", "website": "nvidia.com"},
    {"name": "AMD India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/amd", "website": "amd.com"},
    {"name": "Walmart Global Tech", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/walmart-global-tech", "website": "walmart.com"},
    {"name": "Twitter/X India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/twitter", "website": "x.com"},
    {"name": "LinkedIn India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/linkedin", "website": "linkedin.com"},
    {"name": "Uber India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/uber-com", "website": "uber.com"},
    {"name": "Airbnb India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/airbnb", "website": "airbnb.co.in"},
    {"name": "Goldman Sachs India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/goldman-sachs", "website": "goldmansachs.com"},
    {"name": "Morgan Stanley India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/morgan-stanley", "website": "morganstanley.com"},
    {"name": "JPMorgan India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/jpmorgan-chase", "website": "jpmorganchase.com"},
    {"name": "Barclays India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/barclays", "website": "barclays.in"},
    {"name": "Deutsche Bank India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/deutsche-bank", "website": "db.com"},
    {"name": "HSBC India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/hsbc", "website": "hsbc.co.in"},
    {"name": "Citi India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/citi", "website": "citibank.co.in"},
    {"name": "McKinsey India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/mckinsey", "website": "mckinsey.com"},
    {"name": "BCG India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/boston-consulting-group", "website": "bcg.com"},
    {"name": "Bain India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/bain-and-company", "website": "bain.com"},
    {"name": "Deloitte India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/deloitte", "website": "deloitte.com"},
    {"name": "EY India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/ernstandyoung", "website": "ey.com"},
    {"name": "KPMG India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/kpmg-india", "website": "kpmg.com/in"},
    {"name": "Accenture India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/accenture", "website": "accenture.com"},
    {"name": "Wipro", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/wipro", "website": "wipro.com"},
    {"name": "Infosys", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/infosys", "website": "infosys.com"},
    {"name": "TCS", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/tata-consultancy-services", "website": "tcs.com"},
    {"name": "HCL Technologies", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/hcl-technologies", "website": "hcltech.com"},
    {"name": "Tech Mahindra", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/tech-mahindra", "website": "techmahindra.com"},
    {"name": "Cognizant India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/cognizant", "website": "cognizant.com"},
    {"name": "Capgemini India", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/capgemini", "website": "capgemini.com"},
    {"name": "Mphasis", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/mphasis", "website": "mphasis.com"},
    {"name": "Hexaware", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/hexaware-technologies", "website": "hexaware.com"},
    {"name": "LTIMindtree", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/ltimindtree", "website": "ltimindtree.com"},
    {"name": "Persistent Systems", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/persistent-systems", "website": "persistent.com"},
    {"name": "Zensar", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/zensar-technologies", "website": "zensar.com"},
    {"name": "Mastek", "sector": "Big Tech", "linkedin_url": "https://www.linkedin.com/company/mastek", "website": "mastek.com"},

    # ── Southeast Asia — Singapore ────────────────────────────────────────────
    {"name": "Grab", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/grab", "website": "grab.com"},
    {"name": "Sea Group", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/sea-limited", "website": "sea.com"},
    {"name": "Shopee", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/shopee", "website": "shopee.com"},
    {"name": "Garena", "sector": "Gaming", "linkedin_url": "https://www.linkedin.com/company/garena", "website": "garena.com"},
    {"name": "Nium", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/nium", "website": "nium.com"},
    {"name": "Ninja Van", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/ninja-van", "website": "ninjavan.co"},
    {"name": "Funding Societies", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/funding-societies", "website": "fundingsocieties.com"},
    {"name": "Carro", "sector": "Automotive", "linkedin_url": "https://www.linkedin.com/company/carro-sg", "website": "carro.co"},
    {"name": "PropertyGuru", "sector": "PropTech", "linkedin_url": "https://www.linkedin.com/company/propertyguru", "website": "propertyguru.com.sg"},
    {"name": "Carousell", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/carousell", "website": "carousell.com"},
    {"name": "Advance Intelligence Group", "sector": "AI/ML", "linkedin_url": "https://www.linkedin.com/company/advance-intelligence-group", "website": "advanceintelligence.ai"},
    {"name": "Kredivo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/kredivo", "website": "kredivo.com"},
    {"name": "Aspire", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/aspire-financial-technologies", "website": "aspireapp.com"},
    {"name": "Xendit", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/xendit", "website": "xendit.co"},
    {"name": "StashAway", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/stashaway", "website": "stashaway.com"},
    {"name": "Endowus", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/endowus", "website": "endowus.com"},
    {"name": "Lazada", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/lazada", "website": "lazada.com"},
    {"name": "Syfe", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/syfe", "website": "syfe.com"},
    {"name": "Validus", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/validus-sg", "website": "validus.sg"},
    {"name": "Sleek", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/sleek-sg", "website": "sleek.com"},
    {"name": "Igloo", "sector": "Insurtech", "linkedin_url": "https://www.linkedin.com/company/igloo-sg", "website": "igloo.asia"},
    {"name": "Intellect Design Arena", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/intellect-design-arena", "website": "intellectdesign.com"},
    {"name": "PatSnap", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/patsnap", "website": "patsnap.com"},
    {"name": "Trax Retail", "sector": "Retail Tech", "linkedin_url": "https://www.linkedin.com/company/trax-retail", "website": "traxretail.com"},

    # ── Southeast Asia — Indonesia ─────────────────────────────────────────────
    {"name": "Gojek", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/gojek", "website": "gojek.com"},
    {"name": "GoTo Group", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/goto-group", "website": "goto.co.id"},
    {"name": "Tokopedia", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/tokopedia", "website": "tokopedia.com"},
    {"name": "Traveloka", "sector": "Travel Tech", "linkedin_url": "https://www.linkedin.com/company/traveloka", "website": "traveloka.com"},
    {"name": "OVO", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/ovo-indonesia", "website": "ovo.id"},
    {"name": "DANA Indonesia", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/dana-indonesia", "website": "dana.id"},
    {"name": "Akulaku", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/akulaku", "website": "akulaku.com"},
    {"name": "KoinWorks", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/koinworks", "website": "koinworks.com"},
    {"name": "Modalku", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/modalku", "website": "modalku.co.id"},
    {"name": "Amartha", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/amartha", "website": "amartha.com"},
    {"name": "Sayurbox", "sector": "Agritech", "linkedin_url": "https://www.linkedin.com/company/sayurbox", "website": "sayurbox.com"},
    {"name": "Kopi Kenangan", "sector": "F&B", "linkedin_url": "https://www.linkedin.com/company/kopi-kenangan", "website": "kopikenangan.com"},
    {"name": "Waresix", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/waresix", "website": "waresix.com"},
    {"name": "Shipper", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/shipper-id", "website": "shipper.id"},
    {"name": "Sicepat Ekspres", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/sicepat-ekspres", "website": "sicepat.com"},
    {"name": "Tiket.com", "sector": "Travel Tech", "linkedin_url": "https://www.linkedin.com/company/tiket-com", "website": "tiket.com"},
    {"name": "Bukalapak", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/bukalapak", "website": "bukalapak.com"},
    {"name": "Halodoc", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/halodoc", "website": "halodoc.com"},
    {"name": "Alodokter", "sector": "Healthtech", "linkedin_url": "https://www.linkedin.com/company/alodokter", "website": "alodokter.com"},
    {"name": "Ruangguru", "sector": "EdTech", "linkedin_url": "https://www.linkedin.com/company/ruangguru", "website": "ruangguru.com"},

    # ── Southeast Asia — Vietnam ───────────────────────────────────────────────
    {"name": "VNPay", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/vnpay", "website": "vnpay.vn"},
    {"name": "MoMo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/momo-e-wallet", "website": "momo.vn"},
    {"name": "VNG Corporation", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/vng-corporation", "website": "vng.com.vn"},
    {"name": "Tiki", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/tiki-vn", "website": "tiki.vn"},
    {"name": "KiotViet", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/kiotviet", "website": "kiotviet.vn"},
    {"name": "Base.vn", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/base-vn", "website": "base.vn"},
    {"name": "Sendo", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/sendo-vn", "website": "sendo.vn"},
    {"name": "VNPT Technology", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/vnpt-technology", "website": "vnpt-technology.vn"},
    {"name": "Sky Mavis", "sector": "Gaming/Web3", "linkedin_url": "https://www.linkedin.com/company/sky-mavis", "website": "skymavis.com"},

    # ── Southeast Asia — Malaysia ──────────────────────────────────────────────
    {"name": "AirAsia Digital", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/airasia-digital", "website": "airasia.com"},
    {"name": "iPay88", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/ipay88", "website": "ipay88.com"},
    {"name": "Revenue Monster", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/revenue-monster", "website": "revenuemonster.my"},
    {"name": "StoreHub", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/storehub", "website": "storehub.com"},
    {"name": "Jirnexu", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/jirnexu", "website": "jirnexu.com"},
    {"name": "PolicyStreet", "sector": "Insurtech", "linkedin_url": "https://www.linkedin.com/company/policystreet", "website": "policystreet.com"},
    {"name": "Soft Space", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/soft-space", "website": "soft.space"},
    {"name": "Carsome", "sector": "Automotive", "linkedin_url": "https://www.linkedin.com/company/carsome", "website": "carsome.my"},
    {"name": "iPrice Group", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/iprice-group", "website": "iprice.my"},

    # ── Southeast Asia — Philippines ───────────────────────────────────────────
    {"name": "GCash", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/gcash", "website": "gcash.com"},
    {"name": "Maya Philippines", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/maya-philippines", "website": "maya.ph"},
    {"name": "PayMongo", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/paymongo", "website": "paymongo.com"},
    {"name": "Growsari", "sector": "B2B SaaS", "linkedin_url": "https://www.linkedin.com/company/growsari", "website": "growsari.com"},
    {"name": "Kumu", "sector": "Social Media", "linkedin_url": "https://www.linkedin.com/company/kumu-ph", "website": "kumu.ph"},
    {"name": "Advance", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/advance-ph", "website": "advance.ph"},
    {"name": "Mynt", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/mynt-ph", "website": "mynt.xyz"},

    # ── Southeast Asia — Thailand ──────────────────────────────────────────────
    {"name": "LINE MAN Wongnai", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/line-man-wongnai", "website": "lineman.io"},
    {"name": "Omise", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/omise", "website": "omise.co"},
    {"name": "SCB 10X", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/scb-10x", "website": "scb10x.com"},
    {"name": "True Digital Group", "sector": "Super App", "linkedin_url": "https://www.linkedin.com/company/true-digital-group", "website": "truedigital.com"},
    {"name": "Rabbit Finance", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/rabbit-finance", "website": "rabbitfinance.com"},
    {"name": "Flash Express", "sector": "Logistics", "linkedin_url": "https://www.linkedin.com/company/flash-express", "website": "flashexpress.co.th"},
    {"name": "Pomelo Fashion", "sector": "E-Commerce", "linkedin_url": "https://www.linkedin.com/company/pomelo-fashion", "website": "pomelofashion.com"},
    {"name": "Bitkub", "sector": "Web3/Crypto", "linkedin_url": "https://www.linkedin.com/company/bitkub-online", "website": "bitkub.com"},
    {"name": "Ascend Money", "sector": "Fintech", "linkedin_url": "https://www.linkedin.com/company/ascend-money", "website": "ascendmoney.io"},
]
